import { NextRequest, NextResponse } from 'next/server'
import { FieldPath, type Query } from 'firebase-admin/firestore'
import { adminDb } from '@/lib/firebase/admin'
import { COLLECTIONS } from '@/lib/firebase/collections'
import { verifyAdmin, adminUnauthorized } from '@/lib/admin-auth'
import type { FeedbackPriority, FeedbackStatus, FeedbackType } from '@/types'

const PAGE_SIZE_DEFAULT = 25
const PAGE_SIZE_MAX = 50
const FEEDBACK_TYPES: FeedbackType[] = ['BUG', 'IDEA', 'QUESTION', 'OTHER']
const FEEDBACK_STATUSES: FeedbackStatus[] = ['NEW', 'IN_REVIEW', 'PLANNED', 'RESOLVED', 'CLOSED']
const FEEDBACK_PRIORITIES: FeedbackPriority[] = ['LOW', 'NORMAL', 'HIGH', 'CRITICAL']

type FeedbackFilters = {
  type: FeedbackType | null
  status: FeedbackStatus | null
  priority: FeedbackPriority | null
  q: string | null
}

type Cursor = { v: 2; id: string; scope: string }

function isOneOf<T extends string>(value: string | null, values: readonly T[]): value is T {
  return value !== null && values.includes(value as T)
}

function cursorScope(filters: FeedbackFilters, pageSize: number) {
  // Keep the cursor bound to precisely the result ordering/query that created
  // it. Base64 is opacity rather than an authorization boundary; the admin
  // check remains the authorization gate for every request.
  return JSON.stringify({
    status: filters.status,
    type: filters.type,
    priority: filters.priority,
    q: filters.q,
    pageSize,
  })
}

function parseCursor(value: string | null): Cursor | null | 'INVALID' {
  if (!value) return null
  try {
    const decoded = JSON.parse(Buffer.from(value, 'base64url').toString('utf8'))
    if (
      decoded
      && decoded.v === 2
      && typeof decoded.id === 'string'
      && decoded.id.length > 0
      && decoded.id.length <= 150
      && typeof decoded.scope === 'string'
      && decoded.scope.length <= 300
    ) return { v: 2, id: decoded.id, scope: decoded.scope }
  } catch {
    // Fall through to the uniform invalid-cursor response below.
  }
  return 'INVALID'
}

function encodeCursor(id: string, scope: string) {
  return Buffer.from(JSON.stringify({ v: 2, id, scope }), 'utf8').toString('base64url')
}

// Matches the bounded prefixes generated by buildFeedbackSearchTerms(). A
// manager can search one word/prefix (not arbitrary phrase substring) without
// scanning the collection. This is deliberately explicit instead of silently
// returning incomplete results from a client-side filter.
function normalizeSearchToken(value: string | null): string | null | 'INVALID' {
  if (!value) return null
  const normalized = value
    .normalize('NFKD')
    .toLocaleLowerCase('he-IL')
    .replace(/[^\p{L}\p{N}]+/gu, ' ')
    .trim()

  if (!normalized || normalized.includes(' ') || normalized.length > 40) return 'INVALID'
  return normalized
}

function queryWithFilters(db: ReturnType<typeof adminDb>, filters: FeedbackFilters) {
  let query: Query = db.collection(COLLECTIONS.FEEDBACK)
  if (filters.status) query = query.where('status', '==', filters.status)
  if (filters.type) query = query.where('type', '==', filters.type)
  if (filters.priority) query = query.where('priority', '==', filters.priority)
  if (filters.q) query = query.where('searchTerms', 'array-contains', filters.q)
  return query
}

function serializeFeedback(id: string, data: Record<string, unknown>) {
  const timestamp = (value: unknown) => {
    if (value && typeof value === 'object' && 'toDate' in value && typeof value.toDate === 'function') {
      return value.toDate().toISOString()
    }
    return null
  }

  // Never expose browser fingerprints or internal search index values even to
  // the panel response. The manager gets only the report data required to
  // triage it, plus the manager-only note.
  return {
    id,
    reporterUid: typeof data.reporterUid === 'string' ? data.reporterUid : '',
    reporterEmail: typeof data.reporterEmail === 'string' ? data.reporterEmail : '',
    reporterDisplayName: typeof data.reporterDisplayName === 'string' ? data.reporterDisplayName : '',
    reporterRole: typeof data.reporterRole === 'string' ? data.reporterRole : null,
    type: data.type,
    subject: typeof data.subject === 'string' ? data.subject : '',
    description: typeof data.description === 'string' ? data.description : '',
    status: data.status,
    priority: data.priority,
    pageUrl: typeof data.pageUrl === 'string' ? data.pageUrl : '',
    appVersion: typeof data.appVersion === 'string' ? data.appVersion : null,
    internalNote: typeof data.internalNote === 'string' ? data.internalNote : null,
    // The list response intentionally exposes only presence. The private
    // Storage key is resolved by a separate, admin-authenticated endpoint.
    hasScreenshot: typeof data.screenshotStorageKey === 'string' && data.screenshotStorageKey.length > 0,
    createdAt: timestamp(data.createdAt),
    updatedAt: timestamp(data.updatedAt),
  }
}

export async function GET(request: NextRequest) {
  if (!await verifyAdmin(request)) return adminUnauthorized()

  const { searchParams } = new URL(request.url)
  const typeParam = searchParams.get('type')
  const statusParam = searchParams.get('status')
  const priorityParam = searchParams.get('priority')
  const pageSizeParam = searchParams.get('pageSize')

  if (typeParam && !isOneOf(typeParam, FEEDBACK_TYPES)) {
    return NextResponse.json({ error: 'סוג פנייה לא תקין' }, { status: 400 })
  }
  if (statusParam && !isOneOf(statusParam, FEEDBACK_STATUSES)) {
    return NextResponse.json({ error: 'סטטוס פנייה לא תקין' }, { status: 400 })
  }
  if (priorityParam && !isOneOf(priorityParam, FEEDBACK_PRIORITIES)) {
    return NextResponse.json({ error: 'עדיפות פנייה לא תקינה' }, { status: 400 })
  }

  const pageSize = pageSizeParam === null ? PAGE_SIZE_DEFAULT : Number(pageSizeParam)
  if (!Number.isInteger(pageSize) || pageSize < 1 || pageSize > PAGE_SIZE_MAX) {
    return NextResponse.json({ error: `גודל עמוד חייב להיות בין 1 ל־${PAGE_SIZE_MAX}` }, { status: 400 })
  }

  const q = normalizeSearchToken(searchParams.get('q'))
  if (q === 'INVALID') {
    return NextResponse.json({ error: 'החיפוש תומך במילה או תחילת מילה אחת, עד 40 תווים' }, { status: 400 })
  }

  const filters: FeedbackFilters = {
    type: typeParam as FeedbackType | null,
    status: statusParam as FeedbackStatus | null,
    priority: priorityParam as FeedbackPriority | null,
    q,
  }
  const scope = cursorScope(filters, pageSize)
  const cursor = parseCursor(searchParams.get('cursor'))
  if (cursor === 'INVALID' || (cursor && cursor.scope !== scope)) {
    return NextResponse.json({ error: 'סמן העמוד אינו תקין' }, { status: 400 })
  }
  const db = adminDb()

  try {
    let feedbackQuery = queryWithFilters(db, filters)
      .orderBy('createdAt', 'desc')
      .orderBy(FieldPath.documentId(), 'desc')

    if (cursor) {
      const cursorSnap = await db.collection(COLLECTIONS.FEEDBACK).doc(cursor.id).get()
      if (!cursorSnap.exists) return NextResponse.json({ error: 'סמן העמוד אינו תקין' }, { status: 400 })
      feedbackQuery = feedbackQuery.startAfter(cursorSnap)
    }

    const [pageSnap, countEntries] = await Promise.all([
      feedbackQuery.limit(pageSize + 1).get(),
      Promise.all(FEEDBACK_STATUSES.map(async (status) => {
        const countQuery = queryWithFilters(db, { ...filters, status })
        const aggregate = await countQuery.count().get()
        return [status, aggregate.data().count] as const
      })),
    ])

    const hasMore = pageSnap.docs.length > pageSize
    const docs = hasMore ? pageSnap.docs.slice(0, pageSize) : pageSnap.docs
    const counts = Object.fromEntries(countEntries) as Record<FeedbackStatus, number>

    return NextResponse.json({
      data: docs.map((doc) => serializeFeedback(doc.id, doc.data())),
      pagination: {
        hasMore,
        nextCursor: hasMore ? encodeCursor(docs.at(-1)!.id, scope) : null,
        pageSize,
      },
      counts: {
        ...counts,
        total: Object.values(counts).reduce((sum, count) => sum + count, 0),
      },
    })
  } catch (error) {
    console.error('GET /api/admin/feedback error:', error)
    return NextResponse.json({ error: 'לא הצלחנו לטעון את הפניות' }, { status: 500 })
  }
}
